apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jjobs
spec:
  replicas: 2
  serviceName: jjobs
  selector:
    matchLabels:
      app.kubernetes.io/name: jjobs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jjobs
    spec:      
      terminationGracePeriodSeconds: 180
      containers:
      - name: jjobs
        image: 418591294355.dkr.ecr.ap-northeast-2.amazonaws.com/jjobs:2.10.0-beta
        env:
        - name: MANAGER_WEB_PORT
          value: "7065"
        - name: SERVER_WEB_PORT
          value: "7075"
        - name: SERVER_TCP_PORT
          value: "17075"
        - name: DB_TYPE
          value: <input_your_db_type>
        - name: JDBC_URL
          value: <input_your_jdbc_url>
        - name: DB_USER
          value: <input_your_db_username>
        - name: DB_PASSWD
          value: <input_your_db_password>
        - name: LOGS_BASE
          value: "/logs001/jjobs"
        - name: LOG_KEEP_DATE
          value: "10"
        - name: LOG_DELETE_YN
          value: "Z"
        - name: ON_BOOT
          value: "exceptagent"
        - name: INSTALL_KIND
          value: "F"
        - name: AGENT_GROUP_ID
          value: "1"
        - name: JJOB_SERVICE_NAME
          value: "jjobs.default.svc.cluster.local"
        ports:
        - containerPort: 7065
        - containerPort: 7075
        - containerPort: 17075
        - containerPort: 17076
        - containerPort: 17077
        - containerPort: 17078
        - containerPort: 17079
        - containerPort: 27075
        - containerPort: 27076
        - containerPort: 27077
        - containerPort: 27078
        - containerPort: 27079
        volumeMounts:
        - mountPath: /logs001/jjobs
          name: jjobs-logs
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1"
          limits:
            memory: "2048Mi"
            cpu: "2"
      volumes:
      - name: jjobs-logs
        persistentVolumeClaim:
          claimName: efs-pvc-fargate-ms
