apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jjobs-agent
  labels:
    app: jjobs-agent
  namespace: default
spec:
  replicas: 2
  serviceName: jjobs-agent
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app: jjobs-agent
  template:
    metadata:
      labels:
        app: jjobs-agent
    spec:
      terminationGracePeriodSeconds: 120
      containers:
      - name: jjobs-agent-container
        image: devonlab/jjobs
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","kubectl delete pods $HOSTNAME --force"]
        env:
        - name: AGENT_GROUP_ID
          value: "0"
        - name: JJOBS_SERVER_IP
          value: "jjobs.default.svc.cluster.local"
        - name: SERVER_WEB_PORT
          value: "7075"
        - name: LOGS_BASE
          value: "/logs001/jjobs"
        - name: LOG_KEEP_DATE
          value: "5"
        - name: LOG_DELETE_YN
          value: "Y"
        - name: ON_BOOT
          value: "yes"
        - name: INSTALL_KIND
          value: "A"
        - name: AGENT_CACHE_DIR
          value: "/logs001/jjobs/agent-cache"
        volumeMounts:
        - mountPath: /logs001/jjobs
          name: jjobs-default-log
        resources:
          requests:
            memory: "512Mi"
            cpu: "1"
          limits:
            memory: "1024Mi"
            cpu: "2"
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /engn001/jjobs/agent/healthcheck.sh
          initialDelaySeconds: 300
          periodSeconds: 5
          timeoutSeconds : 10
      volumes:
      - name: jjobs-default-log
        persistentVolumeClaim:
          claimName: efs-pvc-fargate-ms

