apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jjobs
spec:
  replicas: 2
  serviceName: jjobs
  selector:
    matchLabels:
      app.kubernetes.io/name: jjobs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jjobs
    spec:
      terminationGracePeriodSeconds: 36000
      containers:
        - name: jjobs
          image: devonlab/jjobs
          imagePullPolicy: Always
          #securityContext:
            #capabilities:
              #add: ["NET_ADMIN"]
          #lifecycle:
            #preStop:
              #exec:
                #command:
                  #- /bin/sh
                  #- -c
                  #- /pre-stop.sh
            #postStart:
              #exec:
                #command:
                  #- /bin/sh
                  #- -c
                  #- /post-start.sh
          env:
            - name: MANAGER_WEB_PORT
              value: "7065"
            - name: SERVER_WEB_PORT
              value: "7075"
            - name: SERVER_TCP_PORT
              value: "17075"
            - name: DB_TYPE
              value: <input_your_db_type>
            - name: JDBC_URL
              value: <input_your_jdbc_url>
            - name: JDBC_PARAMETERS
              value: <input_your_jdbc_parameters>
            - name: DB_USER
              value: <input_your_db_username>
            - name: DB_PASSWD
              value: <input_your_db_password>
            - name: LOGS_BASE
              value: "/logs001/jjobs"
            - name: LOG_KEEP_DATE
              value: "10"
            - name: LOG_DELETE_YN
              value: "Y"
            - name: ON_BOOT
              value: "exceptagent"
            - name: INSTALL_KIND
              value: "F"
            - name: AGENT_GROUP_ID
              value: "1"
            - name: JJOB_SERVICE_NAME
              value: "jjobs.default.svc.cluster.local"
            - name: LANG
              value: ko_KR.utf8
            #- name: CUSTOM_COMMAND
              #value: "echo 'Hello from env!' && ls -l"
            #- name: API_PRIVATE_TOKEN
              #value: <input_your_api_user_private_token>
          ports:
            - containerPort: 7065
            - containerPort: 7075
            - containerPort: 17075
            - containerPort: 17076
            - containerPort: 17077
            - containerPort: 17078
            - containerPort: 17079
          volumeMounts:
            - mountPath: /logs001/jjobs
              name: jjobs-logs
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1"
            limits:
              memory: "2048Mi"
              cpu: "2"
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /working/liveness.sh
            initialDelaySeconds: 300
            periodSeconds: 5
            timeoutSeconds: 10
          #readinessProbe:
            #exec:
              #command:
                #- /bin/bash
                #- -c
                #- /working/readiness.sh
            #initialDelaySeconds: 60
            #periodSeconds: 5
            #timeoutSeconds: 10
      volumes:
        - name: jjobs-logs
          persistentVolumeClaim:
            claimName: jjobs-nfs-pvc
