apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: batch
  namespace: default
rules:
- apiGroups: [ "" ]
  resources: [ "pods", "pods/log"]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [ "batch" ]
  resources: [ "jobs" ]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-batch
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: batch
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
